Lesson2-task
KrzysztofJV/futurecollars pull request #2
Opened 2022-06-05 16:23 UTC by KrzysztofJV

2022-06-11 10:33 UTC, PawelFC requested changes
Wszystko ok :)

Mały komentarz do nazewnictwa i możemy mergeować!

2022-06-11 10:33 UTC, PawelFC commented on Lesson2/src/main/java/fc/introduction/calculator/Calculator.java
> +    public double subtraction(double firstNumber, double secondNumber) {
Nazewnictwo jest niespójne. Metody powinniśmy nazywać czasownikami (tak jak w przypadku `sum` i `divide` - zsumuj, podziel). `Substraction` oznacza odejmowanie - zmieńmy więc to na `subtract` - odejmij. Wtedy będziemy mieli spójność z nazewnictwem innych metod. 

W programowaniu trzeba bardzo uważać na spójność w nazewnictwie. Jeśli mamy 4 metody i 2 z nich są nazwane czasownikiem, a 2 rzeczownikiem, to jest to dosyć niekonsekwentne. Powinniśmy wszystkie nazwać czasownikami

2022-06-11 10:33 UTC, PawelFC commented on Lesson2/src/main/java/fc/introduction/calculator/Calculator.java
> +    public double multiplication(double firstNumber, double secondNumber) {
to samo, co w przypadku komentarza do metody `subtraction`

2022-06-12 12:24 UTC, KrzysztofJV commented
Już poprawione ;)

2022-07-02 08:11 UTC, merged